Added Rating model with validations and associations
aghour-services/backend pull request #137
Opened 2023-08-19 18:11 UTC by m7madmagdy

2023-08-19 20:46 UTC, Khaledelabady11 approved these changes

2023-09-01 19:51 UTC, a7madM commented on app/controllers/api/ratings_controller.rb
> +    end
remove this endpoint !

2023-09-01 19:55 UTC, a7madM commented on app/views/api/ratings/_rating.json.jbuilder
> +end
remove this partial

2023-09-01 19:57 UTC, a7madM requested changes
check comments

2023-11-28 20:42 UTC, closed without merging